"""added changes

Revision ID: fd3159a887c8
Revises: ed62b83760b6
Create Date: 2023-06-08 10:45:01.399499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3159a887c8'
down_revision = 'ed62b83760b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
